services:
  - type: web         # Это веб-сервис
    name: killhimka # Имя вашего приложения на Render ( можете изменить )
    runtime: java       # !!! Очень важно: Указываем, что это Java приложение !!!
    repo: https://github.com/Killhimka/killhimka.git
    branch: master      # Ваша основная ветка (если у вас 'main', поменяйте)

    # Команда сборки Gradle для создания исполняемого JAR
    buildCommand: "./gradlew bootJar"

    # Команда запуска вашего Spring Boot приложения
    # Убедитесь, что 'killhimka-0.0.1-SNAPSHOT.jar' - это точное имя файла в build/libs/
    startCommand: "java -jar build/libs/killhimka-0.0.1-SNAPSHOT.jar"

    # Переменные окружения
    envVars:
      # Указываем версию Java, которую должен использовать Render
      - key: JAVA_VERSION
        value: "17" # Укажите вашу версию Java, например, 17, 11

      # Настройки базы данных (укажите реальные данные вашей Render PostgreSQL!)
      # Замените localhost:5432, postgres, postgres на данные вашей Render PostgreSQL базы данных.
      - key: DATABASE_URL
        value: "jdbc:postgresql://YOUR_RENDER_POSTGRES_HOST:5432/YOUR_RENDER_POSTGRES_DB"
      - key: POSTGRES_USER
        value: "YOUR_RENDER_POSTGRES_USER"
      - key: POSTGRES_PASSWORD
        value: "YOUR_RENDER_POSTGRES_PASSWORD"