spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d2kvp03ipnbc73fm44lg-a.oregon-postgres.render.com:5432/database_killhimka
    username: database_killhimka_user
    password: FmvggcOyEH12f3DMOrqDMRck4Ls2YbXd

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085